language: c

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - liblua5.2-dev

sudo: required

before_install:
  scripts/install_deps.sh

script:
  - sh ./autogen.sh
  - ./configure
  - make distcheck

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#pkgconf"
    on_success: change
    on_failure: always
