sudo: required
language: minimal
env:
  matrix:
    - ARCH=x86_64
    - ARCH=x86
    - ARCH=aarch64
    - ARCH=armhf
    - ARCH=ppc64le

before_install:
  - "wget 'https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/v0.7.0/alpine-chroot-install' \
        && echo '090d323d887ef3a2fd4e752428553f22a52b87bb  alpine-chroot-install' | sha1sum -c || exit 1"
  - alpine() { /alpine/enter-chroot -u "$USER" "$@"; }

install:
  - sudo sh alpine-chroot-install -a "$ARCH"
      -p 'build-base autoconf automake libtool kyua atf'

script:
  - alpine sh ./autogen.sh
  - alpine ./configure
  - alpine make distcheck

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#pkgconf"
    on_success: change
    on_failure: always
