language: c

compiler:
  - clang
  - gcc

script:
  - ./configure --prefix=/usr
  - make
  - make check

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#pkgconf"
    on_success: change
    on_failure: always
